### ISSUE TITLE
Add Code Quality Badge

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/android-custom-camera-with-live-filter#11]
Add Code Quality badge below the app title in README file

just copy the below code and add it in readme below downloads code 

`[![Codacy Badge](https://api.codacy.com/project/badge/Grade/75ad4b69e2cb402ba8bf82e919a17157)](https://www.codacy.com/app/arshadkazmi42/android-custom-camera-with-live-filter?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=arshadkazmi42/android-custom-camera-with-live-filter&amp;utm_campaign=Badge_Grade)`

**To work on this**
1. Put a comment here who ever is working on it.
2. Also tag this issue in your Pull Request description.

**Note:** Anyone who is not following above two steps, their PR will be rejected

**Comment by PulsarBlow** [comment]
Working on it

**Comment by arshadkazmi42** [comment]
@rabimba Looks good. just need a small change and its ready to be merged

**Comment by arshadkazmi42** [comment]
> Working on it

@rabimba Is already working on it before you. So its @rabimba issue, you can explore our other issues for more bugs

**Comment by PulsarBlow** [comment]
I thought you had to follow this ;)

>> Anyone who is not following above two steps, their PR will be rejected

**Comment by arshadkazmi42** [comment]
@PulsarBlow valid point. @rabimba you did not followed the steps correctly. So we will be taking @PulsarBlow PR.

@PulsarBlow you have created the PR in your forked repo, you should it create it in this repo

**Comment by PulsarBlow** [comment]
@arshadkazmi42 Sorry for that, PR should be good now.

**Comment by rabimba** [comment]
I thought the two steps needed was

1. Put a comment here
2. tag this issue in PR

I think I did both first. But whatever. Your decision

**Comment by arshadkazmi42** [comment]
@rabimba You should have added a comment here first, that you are working on it. You can find more issues in the repo to work on.
