### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/android-custom-camera-with-live-filter#18]
Update readme file to look something like this

https://github.com/arshadkazmi42/android-contacts-scifiui/blob/master/README.md

**Comment by Zeustopher** [comment]
I'd like to take this one on.

@arshadkazmi42 - do you have any screenshot(s) you'd like to have in the updated readme layout?

**Comment by arshadkazmi42** [comment]
@Zeustopher I don't have any screenshots and yes we want some screenshots in readme file.
