### ISSUE TITLE
Add contributors avatar in README

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/android-custom-camera-with-live-filter#21]
Add contributors avatar in  the readme file.
Just copy the below code and paste it in the readme file

`[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-custom-camera-with-live-filter/images/0)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-custom-camera-with-live-filter/links/0)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-custom-camera-with-live-filter/images/1)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-custom-camera-with-live-filter/links/1)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-custom-camera-with-live-filter/images/2)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-custom-camera-with-live-filter/links/2)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-custom-camera-with-live-filter/images/3)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-custom-camera-with-live-filter/links/3)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-custom-camera-with-live-filter/images/4)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-custom-camera-with-live-filter/links/4)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-custom-camera-with-live-filter/images/5)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-custom-camera-with-live-filter/links/5)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-custom-camera-with-live-filter/images/6)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-custom-camera-with-live-filter/links/6)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-custom-camera-with-live-filter/images/7)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-custom-camera-with-live-filter/links/7)`

**Comment by vaibhavdaren** [comment]
may i take it :+1:

**Comment by arshadkazmi42** [comment]
Yes. Go ahead

**Comment by fzd370** [comment]
Is it still open?

**Comment by arshadkazmi42** [comment]
there is already 3 PR's for this. closing it now
