### ISSUE TITLE
Add CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/android-custom-camera-with-live-filter#5]
We need code_of_conduct exactly like this

https://raw.githubusercontent.com/arshadkazmi42/simple-date-validator/master/CODE_OF_CONDUCT.md

with the same file name also.

**Comment by parammittal16** [comment]
Sir I want to work on this. Do u need a same code of conduct without any type of changes

**Comment by arshadkazmi42** [comment]
@parammittal16 Yes. no changes
Go for it. Create a PR
